# Generated by Django 4.1 on 2022-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Загаловок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание поста')),
                ('post_image', models.ImageField(upload_to='', verbose_name='Фото поста')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
