# Generated by Django 4.1 on 2022-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='post_image/', verbose_name='Фото поста'),
        ),
    ]
