# Generated by Django 4.1 on 2022-08-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_post_image_post_image_post_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посcdsты'},
        ),
    ]
