# Generated by Django 4.1 on 2022-08-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('data_of_birth', models.DateTimeField(auto_now_add=True, verbose_name='Дата рождения')),
                ('profile_image', models.ImageField(upload_to='', verbose_name='Фотография профиля')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('info_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на соц сеть')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
