# Generated by Django 4.1 on 2022-08-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_of_birth',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
    ]
